-- Generated by update_sirus_ladder.py
UPDATED_AT = 1786009758
SIRUS_MPLUS_LADDER = {
  ["Bulldogz"] = { bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
  ["Emimicha"] = { rank=6, score=67.5, bestLevel=2, timed=1, total=1, bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Peepeepoo"] = { rank=4, score=135.0, bestLevel=2, timed=1, total=1, bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Saharon"] = { bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
  ["Гномпатруль"] = { rank=7, score=67.5, bestLevel=2, timed=1, total=1, bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Лунабель"] = { rank=1, score=1442.8, bestLevel=19, timed=0, total=1, bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
  ["Метисс"] = { rank=3, score=265.911, bestLevel=2, timed=1, total=1, bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Рассветная"] = { rank=5, score=67.5, bestLevel=2, timed=1, total=1, bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Рубашка"] = { rank=2, score=1088.13, bestLevel=19, timed=0, total=1, bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
  ["Сказочникх"] = { bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
}
