-- Generated by update_sirus_ladder.py
UPDATED_AT = 1784781063
SIRUS_MPLUS_LADDER = {
  ["Burnifikulo"] = { bestTimedLevel=5, bestTimedDungeon="Кузня Крови", bestOverallLevel=5, bestOverallDungeon="Кузня Крови" },
  ["Immoh"] = { bestTimedLevel=5, bestTimedDungeon="Кузня Крови", bestOverallLevel=5, bestOverallDungeon="Кузня Крови" },
  ["Nasterious"] = { rank=6, score=67.5, bestLevel=2, timed=1, total=1, bestTimedLevel=2, bestTimedDungeon="Узилище", bestOverallLevel=2, bestOverallDungeon="Узилище" },
  ["Nixonjkee"] = { rank=3, score=392.848, bestLevel=8, timed=9, total=11, bestTimedLevel=5, bestTimedDungeon="Кузня Крови", bestOverallLevel=5, bestOverallDungeon="Кузня Крови" },
  ["Ntxgod"] = { bestTimedLevel=2, bestTimedDungeon="Узилище", bestOverallLevel=2, bestOverallDungeon="Узилище" },
  ["Shockgun"] = { rank=1, score=629.107, bestLevel=8, timed=12, total=13, bestTimedLevel=5, bestTimedDungeon="Кузня Крови", bestOverallLevel=5, bestOverallDungeon="Кузня Крови" },
  ["Sladescore"] = { rank=7, score=67.5, bestLevel=5, timed=1, total=2, bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Tyhka"] = { rank=2, score=571.155, bestLevel=7, timed=9, total=12, bestTimedLevel=5, bestTimedDungeon="Кузня Крови", bestOverallLevel=5, bestOverallDungeon="Кузня Крови" },
  ["Vladosovich"] = { bestTimedLevel=2, bestTimedDungeon="Узилище", bestOverallLevel=2, bestOverallDungeon="Узилище" },
  ["Вилкувглаз"] = { rank=5, score=135.0, bestLevel=2, timed=3, total=3, bestTimedLevel=2, bestTimedDungeon="Узилище", bestOverallLevel=2, bestOverallDungeon="Узилище" },
  ["Медвежиха"] = { rank=4, score=282.92, bestLevel=8, timed=5, total=5, bestTimedLevel=2, bestTimedDungeon="Узилище", bestOverallLevel=2, bestOverallDungeon="Узилище" },
}
