-- Generated by update_sirus_ladder.py
UPDATED_AT = 1786066560
SIRUS_MPLUS_LADDER = {
  ["Bulldogz"] = { bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
  ["Emimicha"] = { bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Peepeepoo"] = { bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Saharon"] = { bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
  ["Гномпатруль"] = { bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Лунабель"] = { bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
  ["Метисс"] = { bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Рассветная"] = { bestTimedLevel=2, bestTimedDungeon="Бастионы Адского Пламени", bestOverallLevel=2, bestOverallDungeon="Бастионы Адского Пламени" },
  ["Рубашка"] = { bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
  ["Сказочникх"] = { bestOverallLevel=19, bestOverallDungeon="Кузня Крови" },
}
