import json, time, re, urllib.request
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

# ===== НАСТРОЙКИ =====
BASE_ID = 22
WEEK = 1

SCORES_PAGES = 200          # pages for scores (ladder/rank)
RUNS_TIMED_PAGES = 300      # pages for runs?timed=true
RUNS_ALL_PAGES = 300        # pages for runs (all, includes overtime)

WORKERS = 8                 # 4..10 (если 429/ошибки — снизь)

# Пишем Data.lua ВНУТРИ репозитория:
# repo_root/
#   tools/update_sirus_ladder.py   (этот файл)
#   SirusMythicTooltip/Data.lua    (сюда сохраняем)
REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_LUA = REPO_ROOT / "SirusMythicTooltip" / "Data.lua"

API_SCORES = f"https://sirus.su/api/base/{BASE_ID}/leaderboard/challenge/scores"
API_RUNS   = f"https://sirus.su/api/base/{BASE_ID}/leaderboard/challenge/runs"

# mapId -> название данжа (твоя сезонная ротация)
MAP_ID_TO_NAME = {
    542: "Кузня Крови",
    543: "Бастионы Адского Пламени",
    547: "Узилище",
    557: "Гробницы Маны",
    574: "Крепость Утгард",
    600: "Крепость Драк'Тарон",
    602: "Чертоги Молний",
    619: "Королевство Ан'кахет",
}

# ===== HELPERS =====
def fetch_json(url: str):
    req = urllib.request.Request(url, headers={
        "User-Agent": "SirusLadderUpdater/5.1",
        "Accept": "application/json, text/plain, */*",
    })
    with urllib.request.urlopen(req, timeout=40) as r:
        return json.loads(r.read().decode("utf-8", "replace"))

def rows(payload):
    if isinstance(payload, list): return payload
    if isinstance(payload, dict):
        for k in ("data", "items", "rows", "results"):
            v = payload.get(k)
            if isinstance(v, list): return v
        for k in ("result", "payload"):
            v = payload.get(k)
            if isinstance(v, dict):
                for k2 in ("data", "items", "rows", "results"):
                    vv = v.get(k2)
                    if isinstance(vv, list): return vv
    return []

def pick_name(d: dict):
    for k in ("name", "nickname"):
        v = d.get(k)
        if isinstance(v, str) and v: return v
    ch = d.get("character")
    if isinstance(ch, dict):
        v = ch.get("name")
        if isinstance(v, str) and v: return v
    return None

def pick_guid(d: dict):
    for k in ("guid", "memberGuid", "characterGuid"):
        v = d.get(k)
        if isinstance(v, (int, float)): return int(v)
        if isinstance(v, str) and v.isdigit(): return int(v)
    return None

def pick_score(d: dict):
    for k in ("current_score", "score", "points", "rating", "rio", "mplus_score"):
        v = d.get(k)
        if isinstance(v, (int, float)): return float(v)
        if isinstance(v, str):
            try: return float(v.replace(",", "."))
            except: pass
    return None

def pick_best_key(d: dict):
    for k in ("best_key", "bestKey", "key_level", "keystone_level", "max_key", "highest_key"):
        v = d.get(k)
        if isinstance(v, (int, float)): return int(v)
        if isinstance(v, str) and v.isdigit(): return int(v)
    for v in d.values():
        if isinstance(v, str):
            m = re.search(r"\+(\d+)", v)
            if m: return int(m.group(1))
    return None

def pick_counts(d: dict):
    timed = next((d.get(k) for k in ("timed_runs","timed","in_time","timedCount") if isinstance(d.get(k), (int,float))), None)
    total = next((d.get(k) for k in ("total_runs","total","runs","completed","count") if isinstance(d.get(k), (int,float))), None)
    return (int(timed) if timed is not None else None, int(total) if total is not None else None)

def extract_members(run: dict):
    for k in ("members","group","players","party"):
        v = run.get(k)
        if isinstance(v, list):
            out = []
            for m in v:
                if isinstance(m, dict):
                    gid = pick_guid(m)
                    nm = pick_name(m) or m.get("name")
                    if gid and isinstance(nm, str) and nm:
                        out.append((gid, nm))
            if out: return out
    gid = pick_guid(run)
    nm = pick_name(run) or run.get("name")
    if gid and isinstance(nm, str) and nm: return [(gid, nm)]
    return []

def extract_level(run: dict):
    # ТВОЙ API: challengeLevel
    for k in ("challengeLevel", "level", "keyLevel", "key_level", "keystone_level", "mythic_level"):
        v = run.get(k)
        if isinstance(v, (int, float)): return int(v)
        if isinstance(v, str) and v.isdigit(): return int(v)
    return None

def map_name(map_id):
    if map_id is None: return None
    try: map_id = int(map_id)
    except: return None
    return MAP_ID_TO_NAME.get(map_id) or f"mapId:{map_id}"

def lua_dump(db: dict, updated_at: int) -> str:
    def esc(s: str) -> str: return s.replace("\\","\\\\").replace('"','\\"')
    out = ["-- Generated by update_sirus_ladder.py", f"UPDATED_AT = {updated_at}", "SIRUS_MPLUS_LADDER = {"]
    for name in sorted(db):
        info = db[name]
        p = []

        if info.get("rank") is not None: p.append(f'rank={int(info["rank"])}')

        if info.get("score") is not None: p.append(f'score={info["score"]}')
        if info.get("bestLevel") is not None: p.append(f'bestLevel={int(info["bestLevel"])}')
        if info.get("timed") is not None: p.append(f'timed={int(info["timed"])}')
        if info.get("total") is not None: p.append(f'total={int(info["total"])}')

        # timed best (in time)
        if info.get("bestTimedLevel") is not None: p.append(f'bestTimedLevel={int(info["bestTimedLevel"])}')
        if info.get("bestTimedDungeon"): p.append(f'bestTimedDungeon="{esc(info["bestTimedDungeon"])}"')

        # overall best (any completion, includes overtime)
        if info.get("bestOverallLevel") is not None: p.append(f'bestOverallLevel={int(info["bestOverallLevel"])}')
        if info.get("bestOverallDungeon"): p.append(f'bestOverallDungeon="{esc(info["bestOverallDungeon"])}"')

        out.append(f'  ["{esc(name)}"] = {{ {", ".join(p)} }},')
    out.append("}\n")
    return "\n".join(out)

# ===== MAIN =====
def main():
    t0 = time.time()
    updated_at = int(time.time())
    db = {}
    guid2name = {}

    def fetch_scores(p): return p, rows(fetch_json(f"{API_SCORES}?page={p}&week={WEEK}"))
    def fetch_runs_timed(p): return rows(fetch_json(f"{API_RUNS}?page={p}&timed=true"))
    def fetch_runs_all(p): return rows(fetch_json(f"{API_RUNS}?page={p}"))

    print("=== STEP 1: scores (parallel) ===")
    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futs = [ex.submit(fetch_scores, p) for p in range(1, SCORES_PAGES + 1)]
        for fut in as_completed(futs):
            try:
                page, rws = fut.result()
            except Exception:
                continue
            if not rws: continue

            page_size = len(rws)
            for i, row in enumerate(rws):
                if not isinstance(row, dict): continue
                name = pick_name(row)
                if not name: continue

                info = db.get(name, {})

                # rank (место в ладдере)
                info["rank"] = (page - 1) * page_size + (i + 1)

                gid = pick_guid(row)
                if gid: guid2name[gid] = name

                sc = pick_score(row)
                if sc is not None: info["score"] = sc

                bk = pick_best_key(row)
                if bk is not None: info["bestLevel"] = bk

                t, a = pick_counts(row)
                if t is not None: info["timed"] = t
                if a is not None: info["total"] = a

                db[name] = info

    print(f"Scores collected: {len(db)} players")

    print("=== STEP 2: timed runs (parallel) ===")
    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futs = [ex.submit(fetch_runs_timed, p) for p in range(1, RUNS_TIMED_PAGES + 1)]
        for fut in as_completed(futs):
            try:
                rws = fut.result()
            except Exception:
                continue
            if not rws: continue

            for run in rws:
                if not isinstance(run, dict): continue
                lvl = extract_level(run)
                if lvl is None: continue

                dung = map_name(run.get("mapId"))
                members = extract_members(run)
                if not members: continue

                for gid, nm in members:
                    name = guid2name.get(gid) or nm
                    guid2name[gid] = name
                    info = db.get(name, {})

                    cur = info.get("bestTimedLevel")
                    if cur is None or lvl > int(cur):
                        info["bestTimedLevel"] = lvl
                        if dung: info["bestTimedDungeon"] = dung

                    db[name] = info

    print("Timed runs processed.")

    print("=== STEP 3: all runs (parallel) ===")
    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futs = [ex.submit(fetch_runs_all, p) for p in range(1, RUNS_ALL_PAGES + 1)]
        for fut in as_completed(futs):
            try:
                rws = fut.result()
            except Exception:
                continue
            if not rws: continue

            for run in rws:
                if not isinstance(run, dict): continue
                lvl = extract_level(run)
                if lvl is None: continue

                dung = map_name(run.get("mapId"))
                members = extract_members(run)
                if not members: continue

                for gid, nm in members:
                    name = guid2name.get(gid) or nm
                    guid2name[gid] = name
                    info = db.get(name, {})

                    cur = info.get("bestOverallLevel")
                    if cur is None or lvl > int(cur):
                        info["bestOverallLevel"] = lvl
                        if dung: info["bestOverallDungeon"] = dung

                    db[name] = info

    print("All runs processed.")

    OUT_LUA.parent.mkdir(parents=True, exist_ok=True)
    OUT_LUA.write_text(lua_dump(db, updated_at), encoding="utf-8")
    print(f"Saved {len(db)} players to: {OUT_LUA}")
    print(f"Done in {time.time()-t0:.1f}s")

if __name__ == "__main__":
    main()